use frigg;
select content from data join meta on data.digest = meta.data_digest where meta.path = "/opt/frigg/admin/projekt.txt";
select version();
select count(*) from data;
select count(*) from meta;
select count(*) from type;
select count(*) from tag;
select count(*) from systemuser;
select count(*) from usergroup;
select SUM(size) from data;
select SUM(data.size) from meta JOIN data ON meta.data_digest = data.digest;
select SUM(length(content)) FROM data;
select SUM(length(data.content)) FROM meta JOIN data ON meta.data_digest = data.digest;
select digest, metapath, datasize, typename, metaperm, systemusername, usergroupname, metatime, datacompression from frigg.view where metapath like "%" limit 500;
select content from view where digest = "%";
select metapath from view where digest = "%";
INSERT IGNORE INTO tag (name) VALUES ("%");
INSERT IGNORE INTO data_tag (data_digest, tag_id) VALUES ("%", (SELECT id FROM tag WHERE name = "%"));
SELECT name FROM data_tag JOIN tag ON data_tag.tag_id = tag.id WHERE data_tag.data_digest = "%" LIMIT 2;
SELECT typename FROM view WHERE digest = "%" LIMIT 1;
select name from tag ORDER BY name;
select path from data_tag JOIN meta ON data_tag.data_digest = meta.data_digest WHERE data_tag.tag_id = (SELECT id FROM tag WHERE name = "%");
select * from frigg.view;
